package com.github.ralfJoswig.SAP_Connection.constance;

public final class Constance {


	public final static String EMPTY_STRNG = "";
//	public final static String SPACE = " ";
//	public final static String GMT = "GMT";
//	public final static String TIME_ZONE = "Europe/Berlin";
//	public final static String DOT = ".";
//	public final static String SAP_FUNCTION_SAVE = "/SSI/NP_SAVE_BOOKING";
//	public final static String SAP_FUNCTION_GET_TASK = "/SSI/NP_GET_TASKS";
//	public final static String SAP_TABLE_BOOKINGS = "IT_BOOKINGS";
//	public final static String SAP_DEPARTMENT = "ABTLG";
//	public final static String SAP_IMP_DEPARTMENT = "I_ABTEILUNG";
//	public final static String SAP_IMP_USER = "I_USER";
//	public final static String SAP_EXP_TASKS = "ET_TASKS";
//	public final static String SAP_EMPLOYEE = "MITARBEITER";
//	public final static String SAP_PROJECT = "PROJEKT"; 
//	public final static String SAP_ORDER = "AUFTRAG"; 
//	public final static String SAP_TASK = "AUFGABE"; 
//	public final static String SAP_DURATION = "AUFWAND";
//	public final static String SAP_TEXT = "TEXT";
//	public final static String SAP_DATE_FORMAT = "yyyyMMdd";
//	public final static String SAP_DATE = "DATUM";
//	public final static String SAP_COUNT_BOOKINGS = "E_ANZ_BUCHUNGEN";
//	public final static String BUNDLE_NAME = "export.messages";
//	public final static String ELE_ROOT = "root";
//	public final static String ELE_TASKTIME = "TaskTime";
//	public final static String ATT_PROJECT = "Project";
//	public final static String ATT_ORDER = "Order";
//	public final static String ATT_TASK = "Task";
//	public final static String ATT_SUBTASK = "SubTask";
//	public final static String ATT_TEXT = "Text";
//	public final static String ATT_DURATION = "Duration";
//	public final static String PROPERTY_USER_HOME = "user.home";
//	public final static String PROPERTY_FILE_SPARATOR = "file.separator";
//	public final static String FILE_LOG = "NpTT.log";
//	public final static String FILE_BAK = "NpTT.bak";
//	public final static String FILE_SAVE = "NpTT.sav";
//	public final static String FILE_DAT = "NpTT.dat";
//	public final static String FILE_CONF = "NpTT.conf";
//	public final static String ERROR_MSG_TRANSFERHANDLER = "Error TrasferHanlder:";
//	public final static String ERROR_MSG_SAVETOFILE = "Error SaveToFile:";
//	public final static String ERROR_MSG_OPTIONS = "Error Options:";
	public final static String ERROR_MSG_SAPCONNECTION = "Error SapConnection:";
//	public final static String VERSION = "1.0";
//	public final static String ABOUT_TEXT = "\n\nNetProjekt Timetracker\nvon Ralf Joswig";
//	public final static String ERROR_MSG_IMPORT_FROM_SAP = "Error ImportFromSAP:";
//	public final static String TAG_TASKS = "Tasks";
//	public final static String TAG_PROJECT = "Project";
//	public final static String TAG_ORDER = "Order";
//	public final static String TAG_TASK = "Task";
//	public final static String TAG_TEXT = "Text";
//	public final static String TAG_PATH = "Path";
//	public final static String TAG_SUBTASK = "SubTask";
//	public final static String TAG_PROJECTS = "Projects";
	public final static String SAP_SERVER = "SAP_SERVER";
	public final static String CHAR_X = "X";
	public final static String MESSAGE = "MESSAGE";
}
